// local-auth.mjs — serve this repo on localhost WITH live sheet data.
//
// In production the three sheet proxies run as Vercel Edge Functions
// (api/ebtp-proxy, api/zstk-proxy, api/autobtr-proxy), authenticated by the
// SHEETS_SA_* env vars. On localhost neither half exists: static hosting has
// no /api layer, and the credential lives in the gitignored key file
// service-account.json instead of an env var. This file bridges both gaps
// with zero dependencies:
//
//   node local-auth.mjs          → http://127.0.0.1:4173  (default port;
//       override with --port N or PORT=… — browse the dashboards through
//       THIS url so the pages' relative fetch('/api/…') reaches this server)
//     • loads service-account.json into SHEETS_SA_CLIENT_EMAIL /
//       SHEETS_SA_PRIVATE_KEY — the exact vars api/_sheets-sa.js reads — then
//       serves the REAL api/*.js handlers (same code path as production,
//       not a re-implementation);
//     • serves the static dashboards from the repo root on the SAME origin,
//       so every page's relative fetch('/api/…') resolves without changes;
//     • needs no login: index.html already detects localhost (isLocalDev)
//       and skips the auth gate there.
//
//   node local-auth.mjs --env    → writes .env.local (gitignored) with the
//     SHEETS_SA_* pair lifted from service-account.json, for anyone who
//     prefers `vercel dev` over this server.
//
// The key file is read at runtime from service-account.json (repo root,
// gitignored — see SVA.md "The service account"). Never commit it and never
// inline its contents here; this script holds no secrets of its own.

import { createServer } from 'node:http';
import { readFile, writeFile, stat } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const SA_PATH = path.join(ROOT, 'service-account.json');
const argv = process.argv.slice(2);

async function loadServiceAccount() {
  let raw;
  try {
    raw = await readFile(SA_PATH, 'utf8');
  } catch {
    console.error(`local-auth: ${SA_PATH} not found.`);
    console.error('  The key file is local-only (gitignored). Copy the service-account JSON');
    console.error('  exported from GCP to the repo root — see SVA.md, "The service account" —');
    console.error('  then re-run. (For `vercel dev` instead: node local-auth.mjs --env)');
    process.exit(1);
  }
  let sa;
  try {
    sa = JSON.parse(raw);
  } catch (e) {
    console.error(`local-auth: service-account.json is not valid JSON (${e.message})`);
    process.exit(1);
  }
  if (!sa.client_email || !sa.private_key) {
    console.error('local-auth: service-account.json is missing client_email / private_key.');
    process.exit(1);
  }
  return sa;
}

// ── `--env` mode: emit .env.local for `vercel dev`, then stop ──────────────
if (argv.includes('--env')) {
  const sa = await loadServiceAccount();
  const body = [
    '# Generated by `node local-auth.mjs --env` — local sheet auth for vercel dev.',
    '# Same credential pair production sets by hand in Vercel (see SVA.md).',
    '# api/_sheets-sa.js unescapes \\n in the key itself, so \\n-escaped PEM is fine.',
    `SHEETS_SA_CLIENT_EMAIL=${JSON.stringify(sa.client_email)}`,
    `SHEETS_SA_PRIVATE_KEY=${JSON.stringify(sa.private_key)}`,
    '',
  ].join('\n');
  const out = path.join(ROOT, '.env.local');
  await writeFile(out, body, 'utf8');
  console.log(`local-auth: wrote ${out}`);
  console.log(`  SHEETS_SA_CLIENT_EMAIL=${sa.client_email}`);
  process.exit(0);
}

// ── Auth: inject the env pair BEFORE any handler asks Google for a token ───
// api/_sheets-sa.js reads process.env at token time, so setting it here is
// all the wiring the production code needs to run unmodified under Node.
const sa = await loadServiceAccount();
process.env.SHEETS_SA_CLIENT_EMAIL = sa.client_email;
process.env.SHEETS_SA_PRIVATE_KEY = sa.private_key;

// ── The same Edge handlers Vercel runs — imported, not re-implemented ──────
const API_ROUTES = {
  '/api/ebtp-proxy': new URL('./api/ebtp-proxy.js', import.meta.url),
  '/api/zstk-proxy': new URL('./api/zstk-proxy.js', import.meta.url),
  '/api/autobtr-proxy': new URL('./api/autobtr-proxy.js', import.meta.url),
};

const handlerCache = new Map();
async function getHandler(pathname) {
  if (!handlerCache.has(pathname)) {
    handlerCache.set(pathname, (await import(API_ROUTES[pathname])).default);
  }
  return handlerCache.get(pathname);
}

// ── Static files, served from the repo root on the same origin as /api ─────
const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.htm': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.map': 'application/json; charset=utf-8',
  '.csv': 'text/csv; charset=utf-8',
  '.txt': 'text/plain; charset=utf-8',
  '.md': 'text/plain; charset=utf-8',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.webp': 'image/webp',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.webmanifest': 'application/manifest+json',
  '.pdf': 'application/pdf',
  '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
};

function send(res, status, headers, body) {
  if (!res.headersSent) res.writeHead(status, headers);
  res.end(body);
}

// Edge handlers are `(request?) => Response`; pass a Request-shaped argument
// for future handlers that read it — today's three ignore it. The response
// body (CSV text, JSON, or the AutoBTR xlsx ArrayBuffer) is copied through
// verbatim, and CORS is opened for convenience (local-only server, bound to
// 127.0.0.1, so nothing leaves this machine uninvited).
async function serveApi(pathname, res) {
  const handler = await getHandler(pathname);
  const upstream = await handler(new Request(`http://127.0.0.1${pathname}`));
  const headers = {};
  upstream.headers.forEach((v, k) => { headers[k] = v; });
  headers['Access-Control-Allow-Origin'] = '*';
  const buf = Buffer.from(await upstream.arrayBuffer());
  send(res, upstream.status, headers, buf);
}

async function serveStatic(pathname, res) {
  let rel;
  try {
    rel = decodeURIComponent(pathname);
  } catch {
    return send(res, 400, { 'Content-Type': 'text/plain' }, 'Bad request');
  }
  if (rel === '/') rel = '/index.html';
  const file = path.normalize(path.join(ROOT, rel));
  // Traversal guard: never serve anything above the repo root.
  if (!file.startsWith(ROOT + path.sep)) {
    return send(res, 403, { 'Content-Type': 'text/plain' }, 'Forbidden');
  }
  try {
    const info = await stat(file);
    if (!info.isFile()) return send(res, 404, { 'Content-Type': 'text/plain' }, 'Not found');
    const body = await readFile(file);
    const type = MIME[path.extname(file).toLowerCase()] || 'application/octet-stream';
    send(res, 200, {
      'Content-Type': type,
      'Cache-Control': 'no-cache', // always re-read edits while developing
      'Content-Length': body.length,
    }, body);
  } catch {
    send(res, 404, { 'Content-Type': 'text/plain' }, 'Not found');
  }
}

const server = createServer(async (req, res) => {
  try {
    const { pathname } = new URL(req.url, 'http://localhost');
    if (req.method === 'OPTIONS') {
      return send(res, 204, {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, HEAD, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, Authorization',
      });
    }
    if (pathname in API_ROUTES) return await serveApi(pathname, res);
    if (pathname.startsWith('/api/')) {
      return send(res, 404, {
        'Content-Type': 'application/json; charset=utf-8',
        'Access-Control-Allow-Origin': '*',
      }, JSON.stringify({
        error: `No local handler for ${pathname} — local-auth.mjs only mounts the three sheet proxies.`,
      }));
    }
    if (req.method !== 'GET' && req.method !== 'HEAD') {
      return send(res, 405, { 'Content-Type': 'text/plain' }, 'Method not allowed');
    }
    return await serveStatic(pathname, res);
  } catch (e) {
    console.error(`local-auth: ${req.method} ${req.url} failed —`, e.stack || e);
    send(res, 500, { 'Content-Type': 'text/plain' }, 'local-auth: internal error (see terminal)');
  }
});

const portFlag = argv.indexOf('--port');
const port = (portFlag !== -1 && Number(argv[portFlag + 1])) || Number(process.env.PORT) || 4173;

server.on('error', (err) => {
  if (err && err.code === 'EADDRINUSE') {
    console.error(`local-auth: port ${port} is already in use.`);
    console.error('  Stop whatever is listening there, or pick another port:');
    console.error(`    node local-auth.mjs --port ${port + 1}`);
    console.error('  Then browse the dashboards through THAT url — the pages call');
    console.error("  fetch('/api/…') on their own origin, so the server hosting them");
    console.error('  must also be this one.');
    process.exit(1);
  }
  throw err;
});

server.listen(port, '127.0.0.1', () => {
  console.log('local-auth: service account →', sa.client_email);
  console.log(`local-auth: dashboards      → http://127.0.0.1:${port}/`);
  console.log('local-auth: sheet proxies   → /api/ebtp-proxy  /api/zstk-proxy  /api/autobtr-proxy');
  console.log('local-auth: Ctrl+C to stop');
});

